"""Export & Share — generate shareable reports."""

import json
from fastapi import APIRouter, HTTPException
import aiosqlite
from db.database import DB_PATH

router = APIRouter()


@router.get("/export/benchmark/{run_id}")
async def export_benchmark(run_id: str, format: str = "markdown") -> dict:
    """Export a benchmark run as markdown."""
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        async with db.execute("SELECT * FROM benchmark_runs WHERE id = ?", (run_id,)) as cur:
            run = await cur.fetchone()
        if not run:
            raise HTTPException(404, "Run not found")
        async with db.execute(
            "SELECT * FROM benchmark_results WHERE run_id = ? ORDER BY id", (run_id,)
        ) as cur:
            results = [dict(row) async for row in cur]

    summary = json.loads(run["summary_json"] or "{}")
    config = json.loads(run["config_json"] or "{}")

    lines = [
        f"# Benchmark: {run['name'] or 'Untitled'}",
        f"*{run['created_at']}*", "",
        "## Summary",
        f"- Models: {', '.join(config.get('model_ids', []))}",
        f"- Prompts: {len(config.get('prompt_ids', []))}",
        f"- Best tok/s: {summary.get('best_tps', 'N/A')}", "",
        "## Results", "",
        "| Model | Prompt | tok/s | TTFT (ms) | Tokens |",
        "|---|---|---|---|---|",
    ]
    for r in results:
        metrics = json.loads(r["metrics_json"])
        lines.append(f"| {r['model_name']} | {r['prompt_id']} | {metrics.get('throughput_tps', 'N/A')} | {metrics.get('ttft_ms', 'N/A')} | {metrics.get('output_tokens', 'N/A')} |")

    lines.extend(["", "---", "*Generated by Crucible*"])
    return {"markdown": "\n".join(lines), "run_id": run_id}


@router.get("/export/leaderboard")
async def export_leaderboard(format: str = "markdown") -> dict:
    """Export arena leaderboard as markdown."""
    async with aiosqlite.connect(DB_PATH) as db:
        async with db.execute("SELECT * FROM arena_elo ORDER BY elo DESC") as cur:
            rows = []
            async for row in cur:
                rows.append(row)

    lines = [
        "# Model Arena Leaderboard", "",
        "| Rank | Model | ELO | Win Rate | W/L/T | Battles |",
        "|---|---|---|---|---|---|",
    ]
    for i, row in enumerate(rows):
        battles = row[5]
        wins = row[2]
        wr = f"{wins / battles * 100:.1f}%" if battles > 0 else "0%"
        lines.append(f"| {i + 1} | {row[0]} | {row[1]:.0f} | {wr} | {row[2]}/{row[3]}/{row[4]} | {battles} |")

    lines.extend(["", "---", "*Generated by Crucible*"])
    return {"markdown": "\n".join(lines)}


@router.get("/export/profiler")
async def export_profiler(format: str = "markdown") -> dict:
    """Export profiler stats as markdown."""
    async with aiosqlite.connect(DB_PATH) as db:
        async with db.execute("""
            SELECT model_name, COUNT(*) as n, AVG(tps) as avg_tps, MAX(tps) as max_tps,
                   AVG(ttft_ms) as avg_ttft, SUM(output_tokens) as total_tokens
            FROM inference_profiles GROUP BY model_name ORDER BY n DESC
        """) as cur:
            rows = []
            async for row in cur:
                rows.append(row)

    lines = [
        "# Inference Profiler Summary", "",
        "| Model | Requests | Avg tok/s | Max tok/s | Avg TTFT | Total Tokens |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(f"| {row[0]} | {row[1]} | {row[2]:.1f if row[2] else 'N/A'} | {row[3]:.1f if row[3] else 'N/A'} | {row[4]:.0f if row[4] else 'N/A'}ms | {row[5] or 0:,} |")

    lines.extend(["", "---", "*Generated by Crucible*"])
    return {"markdown": "\n".join(lines)}
